import torch
import torch.nn as nn
import torch.nn.functional as F

from scipy.stats import pearsonr

from tangermeme.predict import predict

def outputLen_MaxPool(input_len, kernel_size, padding, stride, dilation):
    """
    Helper function for the use in the DeepSTARR and MultiNet architectures.
    """
    out = torch.floor(((input_len + (2*padding) - (dilation*(kernel_size - 1)) -1)/float(stride)) + 1)
    return(out)


class DeepSTARR(torch.nn.Module):

    """
    Pytorch implementation of the DeepSTARR model.
    Written by Monika.
    """
    #Our batch shape for input x is (batch size, 1, seq length)
    def __init__(self, input_length, input_channel, output_channel1, output_channel2, output_channel3, output_channel4,
                 kernel_size1, kernel_size2, kernel_size3, kernel_size4, stride, kernel_pool,
                 padding, nlayers_cnn, nlayers_fc, output_fc1, output_fc2, prob):
        super(DeepSTARR, self).__init__()
        self.input_length = torch.tensor([input_length])
        self.input_channel = 4
        self.output_channel1 = output_channel1
        self.output_channel2 = output_channel2
        self.output_channel3 = output_channel3
        self.output_channel4 = output_channel4
        self.kernel_size1 = kernel_size1
        self.kernel_size2 = kernel_size2
        self.kernel_size3 = kernel_size3
        self.kernel_size4 = kernel_size4
        self.nlayers_cnn = nlayers_cnn
        self.nlayers_fc = nlayers_fc
        self.stride = 1
        self.padding = 'same'
        self.kernel_pool = 2 # also default stride
        self.prob = prob
                
        # Conv layer 1
        self.conv1 = torch.nn.Conv1d(self.input_channel, self.output_channel1, 
            kernel_size=self.kernel_size1, stride=self.stride, padding=self.padding)

        x_len_out = self.input_length
            
        # Batch Normalization 1
        self.conv1_bn = nn.BatchNorm1d(self.output_channel1)
        self.relu1 = nn.ReLU()
        
        # Max pooling 1
        self.pool = nn.MaxPool1d(kernel_size=self.kernel_pool) # sequence len/K
        x_len_out = outputLen_MaxPool(x_len_out, self.pool.kernel_size, self.pool.padding, self.pool.stride, self.pool.dilation)
        
        current_dim = self.output_channel1
        self.layers_cnn = nn.ModuleList()
        self.layers_fc = nn.ModuleList()
        hidden_dim = [output_channel1, output_channel2, output_channel3, output_channel4]
        kernel_sizes = [kernel_size1, kernel_size2, kernel_size3, kernel_size4]
        outputs_fc = [output_fc1, output_fc2]
        for i in range(1, nlayers_cnn):
            self.layers_cnn.append(torch.nn.Conv1d(current_dim, hidden_dim[i], 
                kernel_size=kernel_sizes[i], stride=self.stride, padding=self.padding))

            self.layers_cnn.append(nn.BatchNorm1d(hidden_dim[i]))
            self.layers_cnn.append(nn.ReLU())
            self.layers_cnn.append(nn.MaxPool1d(kernel_size=self.kernel_pool))
            
            x_len_out = outputLen_MaxPool(x_len_out, self.layers_cnn[-1].kernel_size, self.layers_cnn[-1].padding, self.layers_cnn[-1].stride, self.layers_cnn[-1].dilation)
            current_dim = hidden_dim[i]
            
        self.flatten = nn.Flatten()
        
        input_final_fc = current_dim*int(x_len_out.item())

        for i in range(0, nlayers_fc):
            self.layers_fc.append(nn.Linear(input_final_fc, outputs_fc[i]))
            self.layers_fc.append(nn.BatchNorm1d(outputs_fc[i]))
            self.layers_fc.append(nn.ReLU())
            self.layers_fc.append(nn.Dropout(self.prob))
            input_final_fc = outputs_fc[i]
        
        self.dense_output = nn.Linear(input_final_fc, 1)
        
    def forward(self, x):
        x = self.relu1(self.conv1_bn(self.conv1(x.float())))
        x = self.pool(x)

        for layer in self.layers_cnn:
            x = layer(x)

        x = self.flatten(x)

        for layer in self.layers_fc:
            x = layer(x)

        return self.dense_output(x)
    
    
    def fit(self, 
            training_data,
            optimizer,
            loss_fn,
            X_valid=None,
            y_valid=None,
            max_epochs=100,
            batch_size=64, 
            dtype='float32',
            device='cuda',
            early_stopping=None,
            profile_loader_used=True,
            savepath=None
           ):

        """Fit the model to data and validate it periodically.

        This method controls the training of a BPNet model. It will fit the
        model to examples generated by the `training_data` DataLoader object
        and, if validation data is provided, will validate the model against 
        it at the end of each epoch and return those values.

        Two versions of the model will be saved: the best model found during
        training according to the validation measures, and the final model
        at the end of training. Additionally, a log will be saved of the
        training and validation statistics, e.g. time and performance.


        Parameters
        ----------
        training_data: torch.utils.data.DataLoader
            A generator that produces examples to train on. If n_control_tracks
            is greater than 0, must product two inputs, otherwise must produce
            only one input.

        optimizer: torch.optim.Optimizer
            An optimizer to control the training of the model.

        scheduler: torch.optim.lr_scheduler, optional
            An optional learning rate scheduler which changes the learning rate
            across batches. If None, do not use a scheduler. Default is None.

        X_valid: torch.tensor or None, shape=(n, 4, 2114)
            A block of sequences to validate on periodically. If None, do not
            perform validation. Default is None.

        X_ctl_valid: torch.tensor or None, shape=(n, n_control_tracks, 2114)
            A block of control sequences to validate on periodically. If
            n_control_tracks is None, pass in None. Default is None.

        y_valid: torch.tensor or None, shape=(n, n_outputs, 1000)
            A block of signals to validate against. Must be provided if
            X_valid is also provided. Default is None.

        max_epochs: int
            The maximum number of epochs to train for, as measured by the
            number of times that `training_data` is exhausted. Default is 100.

        batch_size: int, optional
            The number of examples to include in each batch. Default is 64.

        dtype: str or torch.dtype
            The torch.dtype to use when training. Usually, this will be torch.float32
            or torch.bfloat16. Default is torch.float32.

        device: str
            The device to use for training and inference. Typically, this will be
            'cuda' but can be anything supported by torch. Default is 'cuda'.

        early_stopping: int or None, optional
            Whether to stop training early. If None, continue training until
            max_epochs is reached. If an integer, continue training until that
            number of epochs has been hit without improvement in performance. 
            Default is None.
        """

        if X_valid is not None:
            if profile_loader_used:
                y_valid_counts = y_valid.sum(dim=2)
            else:
                y_valid_counts = y_valid
                
            y_valid_counts = torch.log2(1+y_valid_counts)


        dtype = getattr(torch, dtype) if isinstance(dtype, str) else dtype

        iteration = 0
        early_stop_count = 0
        best_r_valid = 0
        #self.logger.start()

        for epoch in range(max_epochs):
            tic = time.time()

            for data in training_data:
                X, y, labels = data[0], data[-2], data[-1]
                X = X.to(device).float()

                if profile_loader_used:
                    y=y.sum(axis=2)

                y=torch.log2(1+y).to(device)

                # Clear the optimizer and set the model to training mode
                optimizer.zero_grad()
                self.train()

                # Make one training step
                with torch.autocast(device_type=device, dtype=dtype):

                    y_pred = self(X)
                    loss = loss_fn(y_pred,y)
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(self.parameters(), 1)
                    optimizer.step()

                iteration += 1

            train_time = time.time() - tic

            # Validate the model at the end of the epoch

            with torch.no_grad():
                self.eval()
                tic = time.time()

                y_valid_pred = predict(self, X_valid, batch_size=batch_size, dtype=dtype, device=device)
                r_valid = pearsonr(y_valid_counts, y_valid_pred)[0][0]

                valid_time = time.time() - tic

                #self.logger.add([epoch, 
                    #iteration, 
                    #train_time, 
                    #valid_time, 
                    #r_valid, 
                    #])

                #self.logger.save("{}.log".format(self.name))
                
                print(f"r valid: {r_valid}")

                if r_valid > best_r_valid:
                    torch.save(self, savepath)
                    best_r_valid = r_valid
                    early_stop_count = -1


            early_stop_count += 1
            if early_stopping is not None and early_stop_count >= early_stopping:
                break

